### ISSUE TITLE
Create a new version of the architecture diagram

### ISSUE THREAD

**Issue by krook** [Pyrrha-Platform/Pyrrha#65]
**Is your feature request related to a problem? Please describe.**
There is [an architecture diagram available in the main Pyrrha repo](https://user-images.githubusercontent.com/3187457/122242264-08903d00-ce78-11eb-944f-804ba4dc683d.png) and used on the https://pyrrha-platform.org/ website. It could be updated to be a bit clearer. It would be great to see alternative visualizations.

**Describe the solution you'd like**
Look at the current diagram and associated steps. Please propose a better visualization.

**Comment by irina2345** [comment]
I'd like to try to come up with better version of the diagram, if that's fine

**Comment by krook** [comment]
Yes, please do @irina2345. Thank you!

**Comment by bargovandrei** [comment]
Hi, 

I looked over the current diagram and over the website and attached here is a new version of the diagram, which I believe would fit much better. I also attached a photo with how the diagram would look on the website so that you can have a better overview, please tell me what you think about it.

![pyrrha](https://user-images.githubusercontent.com/48682450/146733056-614e3d85-0b85-455e-b3db-dca7545514c3.jpg)

![before-after](https://user-images.githubusercontent.com/48682450/146733085-bfe27095-b22e-4016-90a0-7bece640107c.jpg)

**Comment by irina2345** [comment]
Hi,

I looked over the current diagram and over the website and attached here is a new version of the diagram, which I believe would fit much better. I also attached a photo with how the diagram would look on the website so that you can have a better overview, please tell me what you think about it.

![pyrrha](https://user-images.githubusercontent.com/58267511/146764182-5303e4d4-0a0c-4a99-9ae1-a24d8517f697.jpg)

![before-after](https://user-images.githubusercontent.com/58267511/146764208-903df7e8-1192-4304-aac6-ea012d893150.jpg)

**Comment by krook** [comment]
Thank you @irina2345! Sorry for the delay, I'm just back from break. 

This looks great, can you provide the file in a pull request and/or integrate it into the https://github.com/Pyrrha-Platform/Pyrrha-Dashboard React app?

**Comment by krook** [comment]
Thanks again @irina2345. I've pushed the image to the website.
